apiVersion: v1
kind: Service
metadata:
  name: portal-workers
  namespace: compass
spec:
  selector:
    app: portal-workers
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.port }}
  type: ClusterIP
